version = 0.1
[default.deploy.parameters]
stack_name = "sispe"
resolve_s3 = true
s3_prefix = "sispe"
region = "us-east-1"
profile = "sispe"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
